name: reusable
on:
  workflow_call:
 
        

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - run: echo "this job is tested the reusable yml code.The even triggered is =${{ github.event_name }} event."
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
