name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
   Workflow-B-file:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a main-resuable.yml. Then ${{ github.event_name }} event."
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
